[package]
name = "accel-mma84"
version = "0.1.1"
authors = ["Tim Ryan <tim@tessel.io>"]
description = "Driver for an MMA8452Q 3-axis accelerometer."
license = "MIT"

[dependencies]
tessel = "0.2.0"

[[bin]]
name = "tessel-accel"
doc = false
