[package]
name = "servo-pca9685"
version = "0.1.0"
authors = ["Tim Ryan <tim@tessel.io>"]
description = "Driver for a Tessel servo module."
license = "MIT"

[[bin]]
name = "tessel-servo"
doc = false

[dependencies]
tessel = { path = "../tessel", version = "0.3.0" }
